#include<stdio.h>
#include<windows.h>
int main()
{
printf("天气冷了，多喝热水！！！\n");
Sleep(1000);
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
printf("问候你的家人，马没了！！！\n");
return 0;
}
